### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by sbidoul**
Although I do not understand the goal of this fork, allow me to suggest a couple of clarifications.

### CODE REVIEW

**Comment by blaggacao** [comment]
Sure. merged.

**Comment by blaggacao** [comment]
> Although I do not understand the goal of this fork

This is an attempt of unbundling contrib. While `contrib` might work for some people, it doesn't work for all, but some components of it might indeed.

It tries to solve for example [those problems](https://github.com/acsone/click-odoo-contrib/pull/15#issuecomment-428520863) of scope. By decoupling, all those problems become non-existent all of a sudden.

Would you be willing to host `click-odoo-initializer` under `acsone`'s github org? So that it becomes a concerted move? - There is close to nothing I have added so far ...  ... to me that would feel like the right thing to do (and delete this xoe-labs repo).

**Comment by sbidoul** [comment]
Moving click-odoo-initdb to another project would create compatibility issues for people expecting to have it when installing click-odoo-contrib. So, rather no.

**Comment by blaggacao** [comment]
@sbidoul Moving it out and developing it further outside while keeping `contrib` as is? Combined with a classical deprecation notice that doesn't seem too crazy to me... (And honestly, there is no intent on my side of forking this work at all, if it can be avoided)

**Comment by sbidoul** [comment]
Still no, sorry. Too much trouble for no benefit that I'd understand.

**Comment by blaggacao** [comment]
Btw, I plan to enhance other components of contrib, gradually, and I'm sure they would be all "out of scope" to be accepted upstream. I feel: this is an artificial constraint placed upon collaboration by the mere fact of bundling otherwise not related (within the click-odoo scope) components together... This dynamic is virtually forcing into involuntary forking. I don't think that's something that could be avoided without unbundling.

**Comment by sbidoul** [comment]
Let's advise if/when that happens.

**Comment by blaggacao** [comment]
`makepot` is a candidate to be enhanced into a full web late integration capable of doing git-commits, as an example. But I can agree, to demonstrate the problem in a real case (if/when that happens :wink:)... I hope, though, I may ask you to do me a favor and keep those "buts" somewhat in the back of your mind going forward.

**Pull request merged**
